{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "03546071",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "from langchain.document_loaders import TextLoader\n",
    "from langchain.text_splitter import RecursiveCharacterTextSplitter\n",
    "from langchain.embeddings import HuggingFaceEmbeddings\n",
    "from langchain.vectorstores import Chroma\n",
    "from langchain.llms import OpenAI\n",
    "from langchain.prompts import PromptTemplate\n",
    "from langchain.chains import RetrievalQA\n",
    "from flask import Flask, request, jsonify, render_template\n",
    "\n",
    "# 設定環境變量和檔案路徑\n",
    "novel_folder_path = './novelsascii'\n",
    "hf_token_path = \"./hf_token.txt\"\n",
    "open_ai_key_path = \"./open-ai-key.txt\"\n",
    "\n",
    "with open(hf_token_path, \"r\") as file:\n",
    "    hf_token = file.readline().strip()\n",
    "os.environ[\"HUGGINGFACEHUB_API_TOKEN\"] = hf_token\n",
    "\n",
    "with open(open_ai_key_path, \"r\") as file:\n",
    "    open_ai_key = file.readline().strip()\n",
    "\n",
    "# 文本處理和向量資料庫初始化\n",
    "all_paras = []\n",
    "r_splitter = RecursiveCharacterTextSplitter(\n",
    "    chunk_size=200,\n",
    "    chunk_overlap=50,\n",
    "    separators=[\"\\n\\n\", \"\\n\", \"(?<=\\. )\", \" \"]\n",
    ")\n",
    "\n",
    "novel_files = [f for f in os.listdir(novel_folder_path) if f.endswith('.txt')]\n",
    "for file_name in novel_files:\n",
    "    file_path = os.path.join(novel_folder_path, file_name)\n",
    "    loader = TextLoader(file_path)\n",
    "    data = loader.load()\n",
    "    paras = r_splitter.split_documents(data)\n",
    "    all_paras.extend(paras)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "99f84c5f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 263, in _notify_one\n",
      "    sub.callback([embedding])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 393, in _write_metadata\n",
      "    self._insert_record(cur, record, True)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 227, in _insert_record\n",
      "    self._update_metadata(cur, id, record[\"metadata\"])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 253, in _update_metadata\n",
      "    cur.execute(sql, params)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\user\\AppData\\Local\\Temp\\ipykernel_2500\\2528071441.py\", line 3, in <module>\n",
      "    vectordb = Chroma.from_documents(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 613, in from_documents\n",
      "    return cls.from_texts(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 577, in from_texts\n",
      "    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 209, in add_texts\n",
      "    self._collection.upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\models\\Collection.py\", line 298, in upsert\n",
      "    self._client._upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\segment.py\", line 284, in _upsert\n",
      "    self._producer.submit_embedding(coll[\"topic\"], r)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 142, in submit_embedding\n",
      "    self._notify_all(topic_name, embedding_record)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 249, in _notify_all\n",
      "    self._notify_one(sub, embedding)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 266, in _notify_one\n",
      "    logger.error(\n",
      "Message: 'Exception occurred invoking consumer for subscription d50570c3-d013-4294-8e11-20697bc1bdaato topic persistent://default/default/78adc349-d3fa-4a8b-8c5f-e907d1a78b28 for embedding id 9f30aaf8-97c3-11ee-8980-4c034fc12554 '\n",
      "Arguments: (KeyboardInterrupt(),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 263, in _notify_one\n",
      "    sub.callback([embedding])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 393, in _write_metadata\n",
      "    self._insert_record(cur, record, True)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 227, in _insert_record\n",
      "    self._update_metadata(cur, id, record[\"metadata\"])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 253, in _update_metadata\n",
      "    cur.execute(sql, params)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\user\\AppData\\Local\\Temp\\ipykernel_2500\\2528071441.py\", line 3, in <module>\n",
      "    vectordb = Chroma.from_documents(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 613, in from_documents\n",
      "    return cls.from_texts(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 577, in from_texts\n",
      "    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 209, in add_texts\n",
      "    self._collection.upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\models\\Collection.py\", line 298, in upsert\n",
      "    self._client._upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\segment.py\", line 284, in _upsert\n",
      "    self._producer.submit_embedding(coll[\"topic\"], r)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 142, in submit_embedding\n",
      "    self._notify_all(topic_name, embedding_record)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 249, in _notify_all\n",
      "    self._notify_one(sub, embedding)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 266, in _notify_one\n",
      "    logger.error(\n",
      "Message: 'Exception occurred invoking consumer for subscription d50570c3-d013-4294-8e11-20697bc1bdaato topic persistent://default/default/78adc349-d3fa-4a8b-8c5f-e907d1a78b28 for embedding id 9f311ecb-97c3-11ee-aa62-4c034fc12554 '\n",
      "Arguments: (KeyboardInterrupt(),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 263, in _notify_one\n",
      "    sub.callback([embedding])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 393, in _write_metadata\n",
      "    self._insert_record(cur, record, True)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 227, in _insert_record\n",
      "    self._update_metadata(cur, id, record[\"metadata\"])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 253, in _update_metadata\n",
      "    cur.execute(sql, params)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\user\\AppData\\Local\\Temp\\ipykernel_2500\\2528071441.py\", line 3, in <module>\n",
      "    vectordb = Chroma.from_documents(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 613, in from_documents\n",
      "    return cls.from_texts(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 577, in from_texts\n",
      "    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 209, in add_texts\n",
      "    self._collection.upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\models\\Collection.py\", line 298, in upsert\n",
      "    self._client._upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\segment.py\", line 284, in _upsert\n",
      "    self._producer.submit_embedding(coll[\"topic\"], r)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 142, in submit_embedding\n",
      "    self._notify_all(topic_name, embedding_record)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 249, in _notify_all\n",
      "    self._notify_one(sub, embedding)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 266, in _notify_one\n",
      "    logger.error(\n",
      "Message: 'Exception occurred invoking consumer for subscription d50570c3-d013-4294-8e11-20697bc1bdaato topic persistent://default/default/78adc349-d3fa-4a8b-8c5f-e907d1a78b28 for embedding id 9f311ed0-97c3-11ee-84ae-4c034fc12554 '\n",
      "Arguments: (KeyboardInterrupt(),)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 263, in _notify_one\n",
      "    sub.callback([embedding])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 393, in _write_metadata\n",
      "    self._insert_record(cur, record, True)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 227, in _insert_record\n",
      "    self._update_metadata(cur, id, record[\"metadata\"])\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 255, in _update_metadata\n",
      "    self._insert_metadata(cur, id, metadata)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\segment\\impl\\metadata\\sqlite.py\", line 320, in _insert_metadata\n",
      "    cur.execute(sql, params)\n",
      "KeyboardInterrupt\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 687, in format\n",
      "    record.message = record.getMessage()\n",
      "                     ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\logging\\__init__.py\", line 377, in getMessage\n",
      "    msg = msg % self.args\n",
      "          ~~~~^~~~~~~~~~~\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\traitlets\\config\\application.py\", line 992, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 711, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n",
      "    await result\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 411, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 531, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3006, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3061, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3266, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3445, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3505, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\user\\AppData\\Local\\Temp\\ipykernel_2500\\2528071441.py\", line 3, in <module>\n",
      "    vectordb = Chroma.from_documents(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 613, in from_documents\n",
      "    return cls.from_texts(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 577, in from_texts\n",
      "    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\langchain\\vectorstores\\chroma.py\", line 209, in add_texts\n",
      "    self._collection.upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\models\\Collection.py\", line 298, in upsert\n",
      "    self._client._upsert(\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\api\\segment.py\", line 284, in _upsert\n",
      "    self._producer.submit_embedding(coll[\"topic\"], r)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 142, in submit_embedding\n",
      "    self._notify_all(topic_name, embedding_record)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 249, in _notify_all\n",
      "    self._notify_one(sub, embedding)\n",
      "  File \"C:\\Users\\user\\anaconda3\\Lib\\site-packages\\chromadb\\db\\mixins\\embeddings_queue.py\", line 266, in _notify_one\n",
      "    logger.error(\n",
      "Message: 'Exception occurred invoking consumer for subscription d50570c3-d013-4294-8e11-20697bc1bdaato topic persistent://default/default/78adc349-d3fa-4a8b-8c5f-e907d1a78b28 for embedding id 9f311ed5-97c3-11ee-bba6-4c034fc12554 '\n",
      "Arguments: (KeyboardInterrupt(),)\n",
      "\n",
      "KeyboardInterrupt\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# print(f\"Total paragraphs processed: {len(all_paras)}\")\n",
    "\n",
    "vectordb = Chroma.from_documents(\n",
    "    documents=all_paras,\n",
    "    embedding=HuggingFaceEmbeddings(),\n",
    "    persist_directory='./chroma_db',\n",
    ")\n",
    "\n",
    "def get_answer(query):\n",
    "    new_line = '\\n'\n",
    "    template = f\"Use the following pieces of context to answer truthfully.{new_line}If the context does not provide the truthful answer, make the answer as truthful as possible.{new_line}Use 15 words maximum. Keep the response as concise as possible.{new_line}{{context}}{new_line}Question: {{question}}{new_line}Response: \"\n",
    "    QA_CHAIN_PROMPT = PromptTemplate(input_variables=[\"context\", \"question\"], template=template)\n",
    "\n",
    "    llm = OpenAI(openai_api_key=open_ai_key)\n",
    "    qa_chain = RetrievalQA.from_chain_type(llm,\n",
    "                                           retriever=vectordb.as_retriever(),\n",
    "                                           return_source_documents=True,\n",
    "                                           chain_type_kwargs={\"prompt\": QA_CHAIN_PROMPT})\n",
    "\n",
    "    result = qa_chain({\"query\": query})\n",
    "    return result[\"result\"]\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1296f7eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "app = Flask(__name__)\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "    return render_template('index.html')\n",
    "\n",
    "@app.route('/chat', methods=['POST'])\n",
    "def chat():\n",
    "    data = request.json\n",
    "    input_text = data['message']\n",
    "    response = get_answer(input_text)\n",
    "    return jsonify({\"response\": response})\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
